spring:
  application:
    name: v2

  datasource:
    url: jdbc:mariadb://127.0.0.1:3308/madotradev2?characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "000620"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
